### PR TITLE
fix: use `html_url` instead of `url` for projects

### PR DESCRIPTION
**Pull request by arunsathiya**
In the projects section of the homepage, link to the human-readable HTML URL rather than the machine-consumable API URL

### CODE REVIEW

**Comment by arunsathiya** [comment]
Ignore the commits history here. It's due to my `--fill-verbose` usage: `gh pr create --fill-verbose`, and failure to create the feature branch before committing.

**Comment by sharunkumar** [comment]
> Ignore the commits history here

Going to squash merge anyways

**Comment by sharunkumar** [comment]
@arunsathiya I'll update the title and description so that it would be appropriate when squash-merging

**Review by sharunkumar — APPROVED** [review]
LGTM on local dev

**Pull request merged**
